apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blue-green-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /active
          backend:
            serviceName: rollout-ngnix-active
            servicePort: 8080
