apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app
spec:

  analysis:
    successfulRunHistoryLimit: 3
    unsuccessfulRunHistoryLimit: 3

  selector:
    matchLabels:
      app: ngnix

  template:
    metadata:
      labels:
        app: ngnix
    spec:
      containers:
      - name: ngnix
        image: nginx:1.19.1
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 10m

  rollbackWindow:
    revisions: 3

  strategy:

    blueGreen:

      activeService: rollout-ngnix-active # <- matches Active Service metadata 
      previewService: rollout-ngnix-preview # <- matches Preview Service metadata

      prePromotionAnalysis:
        templates:
        - templateName: pre-promotion-analysis
        args:
        - name: rollout-ngnix-preview

      postPromotionAnalysis:
        templates:
        - templateName: post-promotion-analysis

      previewReplicaCount: 2
      autoPromotionEnabled: true
      autoPromotionSeconds: 1
      scaleDownDelaySeconds: 30

      # 0 means not to scale down
      abortScaleDownDelaySeconds: 30
