apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green
spec:
  replicas: 2

  analysis:
    successfulRunHistoryLimit: 3
    unsuccessfulRunHistoryLimit: 3

  selector:
    matchLabels:
      app: blue-green

  template:
    metadata:
      labels:
        app: blue-green
    spec:
      containers:
      - name: rollout-demo
        image: argoproj/rollouts-demo:green
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080

  rollbackWindow:
    revisions: 3

  strategy:
    blueGreen:
      activeService: rollout-ngnix-active # <- matches Active Service metadata
      previewService: rollout-ngnix-preview # <- matches Preview Service metadata
      prePromotionAnalysis:
        templates:
        - templateName: success-rate
      autoPromotionEnabled: false

---
kind: Service
apiVersion: v1
metadata:
  name: rollout-ngnix-active # <- active
spec:
  selector:
    app: blue-green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  - protocol: TCP
    port: 443
    targetPort: 8080
    name: https
---
kind: Service
apiVersion: v1
metadata:
  name: rollout-ngnix-preview # <- preview
spec:
  selector:
    app: blue-green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  - protocol: TCP
    port: 443
    targetPort: 8080
    name: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blue-green-ingress
  annotations:
    alb.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: blue-green.cnoe.localtest.me
    http:
      paths:
        - backend:
            service:
              name: rollout-ngnix-active
              port:
                name: https
          path: /
          pathType: Prefix
